### ISSUE TITLE
Pretrained vectors were supported previously - why was support removed?

### ISSUE THREAD

**Issue by aryavohra04** [tensorflow/nmt#104]
In commit d7d2337df0f0522321d363ab1099358e1e77d5dc, flags for pretrained vectors were removed. It doesn't seem like any logic was removed, can support be added again?

**Comment by oahziur** [comment]
@aryavohra04 We removed the flag to simplify the tutorial, and there isn't any logic for loading pre-trained embedding in the code.

**Comment by aryavohra04** [comment]
@oahziur will logic be written for loading pretrained embeddings?

**Comment by kmario23** [comment]
@oahziur It would be nice to have such pretrained embedding options so that much powerful externally trained embeddings can be fed into the seq2seq training model. Is the option likely to be re-introduced?

**Comment by yapingzhao** [comment]
Hi,
I want to use the --embed_prefix option to use my own trained word vector (word2vec).
But,An error occurred while I was running the command
python -m nmt.nmt
--src=vi --tgt=en
--num_units=300
--embed_prefix=nmt/nmt_data/vector
error:"All embedding size should be size."
If you have any suggestions, please give me some suggestions, thank you very much!
