### ISSUE TITLE
How to make BeamSearch work together with AttentionWrapper?

### ISSUE THREAD

**Issue by o-github-o** [tensorflow/nmt#105]
I Want to use Attention during training phase(with Basic decoder),but I want to use BeamSearchDecoder During infer phase ,How I can do it,I have got in trouble a long time

**Comment by oahziur** [comment]
@o-github-o Hi, we build separate graphs for inference and training to achieve this in the tutorial. 

During the training time, we use `tf.contrib.seq2seq.TrainingHelper` with `tf.contrib.seq2seq.BasicDecoder`. During the inference time, we use the `tf.contrib.seq2seq.BeamSearchDecoder` to enable beam search.

You can take a look at the [_build_decoder](https://github.com/tensorflow/nmt/blob/master/nmt/model.py#L293) method in model.py.

**Comment by o-github-o** [comment]
@oahziur Thank you a lot, your method is work for me , my program work out
