### ISSUE TITLE
Is tensorflow-nightly necessary?

### ISSUE THREAD

**Issue by zhangpengGenedock** [tensorflow/nmt#111]
Is tensorflow-nightly necessary? or just after a specific tensorflow version like 1.3.0 can work?
why does it has that restrict, and it leads to the slow training, because the unsupport for gpu.

**Comment by oahziur** [comment]
@zhangpengGenedock The master requires nightly so we can add the latest features to the tutorial. You can check out the [tf-1.2 branch](https://github.com/tensorflow/nmt/tree/tf-1.2) if you want to use tensorflow version 1.3.0.

**Comment by zhangpengGenedock** [comment]
thanks, and is there a different instructions between tf-1.2 branch and master branch?

**Comment by oahziur** [comment]
I don't think there are much different on instructions now, but they may be different in the future. The instructions in the [README](https://github.com/tensorflow/nmt/blob/tf-1.2/README.md) file in the branch should contain the up to date instructions for tensorflow version 1.2 and 1.3.

**Comment by kmario23** [comment]
I don't think the nightly version is necessary because this line checks for whether TF version is >= 1.2.1
https://github.com/tensorflow/nmt/blob/master/nmt/train.py#L33

```
def check_tensorflow_version():
    if tf.__version__ < "1.2.1":  
        raise EnvironmentError("Tensorflow version must >= 1.2.1")
```

So, I guess it will work fine for versions >= 1.2.1
