### ISSUE TITLE
why need vocabulary file?

### ISSUE THREAD

**Issue by zhangpengGenedock** [tensorflow/nmt#113]
when i run the script why do I need vocabulary file?
Because definitely you can get it from the train file automaticly.

**Comment by kmario23** [comment]
Here, they are using an approach called `subword` units to combat the rare words(UNK) problem. So, the vocabulary files has to be generated using [subword scripts](https://github.com/rsennrich/subword-nmt). It is this vocabulary files that you feed into tensorflow-nmt for training. Such a system achieves higher translation accuracy than the one trained on raw text (i.e. without subword units.)

**Comment by zhangpengGenedock** [comment]
@kmario23 thank you!

**Comment by kmario23** [comment]
First three tokens must be <unk>, <start> and <eos>. Other than that it doesn't matter, if you do the sorting consistently. However, if you're using subword units, which you should, then the vocab file is automatically generated.
