### ISSUE TITLE
AttributeError: 'MapDataset' object has no attribute 'apply'

### ISSUE THREAD

**Issue by harishdamera** [tensorflow/nmt#118]
AttributeError: 'MapDataset' object has no attribute 'apply'

I installed Tensorflow Nightly, but still have this error.

**Comment by h312903294** [comment]
I have too,my tensorflow version is 1.2.1

**Comment by oahziur** [comment]
@harishdamera Are you using the latest Nightly? Maybe do `pip install tf-nightly --upgrade`?

You should see '1.4.0-dev20170920' when you check the tf.__version__ string.


@h312903294 You should use the [tf-1.2 branch](https://github.com/tensorflow/nmt/tree/tf-1.2) for tensorflow version 1.2.1.

**Comment by harishdamera** [comment]
Even if I use "pip install tf-nightly --upgrade" , it is installing tf_nightly-1.3.0.dev20170822 .

Not 1.4.0 version.

**Comment by harishdamera** [comment]
What version of tensor flow do u recommend?

**Comment by harishdamera** [comment]
issue resolved. Thanks.
