### ISSUE TITLE
Will stop and rerun continue last progress?

### ISSUE THREAD

**Issue by zhangpengGenedock** [tensorflow/nmt#126]
When I run this model, Will stop and rerun continue last progress?

**Comment by oahziur** [comment]
If you rerun the exactly same command, it will resume the training progress
from the latest checkpoint as long as you didn’t clear the “out_dir”
generated by previous training command.

**Comment by kmario23** [comment]
@oahziur During rerun, is it possible to use a different `vocabulary size` (ideally a larger number) than that was used in the previous run?

**Comment by zhangpengGenedock** [comment]
@oahziur thank you!
