### ISSUE TITLE
OsError: Tensorflow version must >= 1.4.0.dev

### ISSUE THREAD

**Issue by paleuribe** [tensorflow/nmt#143]
When I run the first example (Vietnamese-English), it appears the message "OsError: Tensorflow version must >= 1.4.0.dev". I have updated Tensorflow, but the last version still is 1.3.0 . There is a 1.4.0-rc version (https://github.com/tensorflow/tensorflow/releases/tag/v1.4.0-rc0), but is a pre-release. How can I fix this?

**Comment by tkngoutham** [comment]
simple hack :
change the version number to 1.0.0.dev or latest 1.x version u have in nmt/utils/misc_utils.py

original :
def check_tensorflow_version():
  min_tf_version = "1.4.0-dev"
  if tf.__version__ < min_tf_version:
    raise EnvironmentError("Tensorflow version must >= %s" % min_tf_version)

changed:
def check_tensorflow_version():
  min_tf_version = "1.0.0-dev"
  if tf.__version__ < min_tf_version:
    raise EnvironmentError("Tensorflow version must >= %s" % min_tf_version)



worked for me....!

**Comment by oahziur** [comment]
@paleuribe @tkngoutham You need to install tf-nightly if you want to use the master branch.

Otherwise, you can use the [tf-1.2 branch](https://github.com/tensorflow/nmt/tree/tf-1.2) for released versions.

**Comment by paleuribe** [comment]
Thanks, @tkngoutham @oahziur, but I have installed the last version of Tensorflow (1.3.0), and tf-nightly. @tkngoutham , how can I make that change?

**Comment by tkngoutham** [comment]
the function check_tensorflow_version is in file nmt/utils/misc_utils.py
@oahziur  I did as u said and it worked for me...!

**Comment by paleuribe** [comment]
@oahziur I uninstalled and reinstalled tf-nightly, and now it works, thanks!
