### ISSUE TITLE
Oops！ error when training own data 

### ISSUE THREAD

**Issue by SuperYm** [tensorflow/nmt#148]
InvalidArgumentError (see above for traceback): assertion failed: [All values in memory_sequence_length must greater than zero.] [Condition x > 0 did not hold element-wise:] [x (dynamic_seq2seq/decoder/tile_batch_1/Reshape:0) = ] [24 24 24...]
	 [[Node: dynamic_seq2seq/decoder/decoder/while/BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/cell_0_attention/attention/assert_positive/assert_less/Assert/Assert = Assert[T=[DT_STRING, DT_STRING, DT_STRING, DT_INT32], summarize=3, _device="/job:localhost/replica:0/task:0/device:CPU:0"](dynamic_seq2seq/decoder/decoder/while/BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/cell_0_attention/attention/assert_positive/assert_less/All/_196, dynamic_seq2seq/decoder/decoder/while/BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/cell_0_attention/attention/assert_positive/assert_less/Assert/Assert/data_0, dynamic_seq2seq/decoder/decoder/while/BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/cell_0_attention/attention/assert_positive/assert_less/Assert/Assert/data_1, dynamic_seq2seq/decoder/decoder/while/BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/cell_0_attention/attention/assert_positive/assert_less/Assert/Assert/data_2, dynamic_seq2seq/decoder/decoder/while/BeamSearchDecoderStep/multi_rnn_cell/cell_0_attention/cell_0_attention/attention/assert_positive/assert_less/Less/Enter/_198)]]
	 [[Node: dynamic_seq2seq/encoder/rnn/while/Switch_2/_276 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1232_dynamic_seq2seq/encoder/rnn/while/Switch_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:1"](^_cloopdynamic_seq2seq/encoder/rnn/while/rnn/multi_rnn_cell/cell_2/cell_2/basic_lstm_cell/add/y/_102)]]
i just don't know what makes this error happen.help please！ thanks!

**Comment by oahziur** [comment]
You have the save issue as https://github.com/tensorflow/nmt/issues/140. 

Basically, you have zero length sequence in your own data.
