### ISSUE TITLE
Problem with Bahdanau-style Attention

### ISSUE THREAD

**Issue by DaoD** [tensorflow/nmt#160]
Hi,
In nmt, it support to use Bahdanau-style attention, but in the tensorflow api document, when use this style attention, we need to set output_attention=False when call AttentionWrapper, but in nmt model, there isnt any difference between Bahdanau-style and Luong-style attention when call this class.
However is it a bug?
Thx a lot.

**Comment by oahziur** [comment]
@DaoD Yes, I think you are right.

Our implementation uses Bahdanau attention mechanism, but the `standard` attention architecture doesn't use the exact same architecture as the original paper. I will add a flag to control the `output_attention`, so you can try the original attention architecture.
