### ISSUE TITLE
Is there any preprocessing script for en-de translation like those for de-en and vi-en?

### ISSUE THREAD

**Issue by anglil** [tensorflow/nmt#18]
I'm wondering if there is nay preprocessing script for en-de translation so that I can try NMT myself and see if the result matches the numbers published in this tutorial? Thanks.

**Comment by oahziur** [comment]
Hi @anglil, We use data generated by the  [wmt16_en_de.sh](https://github.com/tensorflow/nmt/blob/master/nmt/scripts/wmt16_en_de.sh) for both de-en and en-de translation training.
