### ISSUE TITLE
How should `source_sequence_length` and `decoder_lengths` be passed in?

### ISSUE THREAD

**Issue by nave01314** [tensorflow/nmt#187]
I'm using the tutorial to develop an NMT model but it does not explain the purpose of `sequence_length` either in this code snippet:
```
encoder_outputs, encoder_state = tf.nn.dynamic_rnn(
    encoder_cell, encoder_emb_inp,
    sequence_length=source_sequence_length, time_major=True)
```
or this one:
```
helper = tf.contrib.seq2seq.TrainingHelper(
    decoder_emb_inp, decoder_lengths, time_major=True)
```
and the online API is not helpful in this case. In `model.py`, an iterator object is used, but the significance of this is unclear.

Should `source_sequence_length` and `decoder_lengths` be passed in as placeholders? (I believe) that since all the inputs are padded to the same length during batching, there is no way for the graph to know the lengths without having extra placeholders, but this seems wasteful.

In fact -- and this is probably a separate question, but it is also not addressed in the explanation -- why do all the inputs need to be padded to the same size to begin with?

**Comment by oahziur** [comment]
@nave01314 The `source_sequence_length` and `decoder_lengths` for training are calculated before we pad the source sequence and the target sequence. You can checkout the code [here](https://github.com/tensorflow/nmt/blob/master/nmt/utils/iterator_utils.py#L145) for getting the sequence length.

It is very common to pad sequential data, so `dynamic_rnn` can evaluate the full batch until the max sequence length in the batch. Note that the inputs to `dynamic_rnn` has to be a tensor with shape [batch_size, **max_time**, ...].

**Comment by fooSynaptic** [comment]
@oahziur i still cannot control the length of decode sequence even i set the tgt_max_len. I spend lots of time to find the wrappers about this parameter, can you help me ?
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/19420328/51380574-fbf34780-1b4c-11e9-9b08-034085a7c508.png">
