### ISSUE TITLE
WMT results do not correspond to a WMT task

### ISSUE THREAD

**Issue by kpu** [tensorflow/nmt#191]
The download script https://github.com/tensorflow/nmt/blob/master/nmt/scripts/wmt16_en_de.sh corresponds to the parallel data from WMT 2016.  But your table https://github.com/tensorflow/nmt#wmt-english-german--full-comparison only reports results on newstest2014 and newstest2015, not newstest2016.  So your system was trained on more parallel data (WMT 2016) than systems that appear as "WMT SOTA" in the table (WMT 2014 and 2015).  

I also contend that the term "WMT SOTA" i.e. "state of the art" should include WMT 2017 baselines.

**Comment by lmthang** [comment]
Hi Kenneth,

Thanks for the the comments! Yes, we will improve by reporting results on newstest2016 + adding WMT'16 SOTA results from http://matrix.statmt.org/. Does that sound good?

FWIW, we were trying to keep the tutorial simple by not reporting results of both models trained on WMT'14 and WMT'16 data. If we compare WMT de-en data across 3 years ([2014](http://www.statmt.org/wmt14/translation-task.html), [2015](http://www.statmt.org/wmt15/translation-task.html), [2016](http://www.statmt.org/wmt16/translation-task.html)), the only data source that changes is News Commentary (5% of total data); the data sizes go from 77MB (2014) -> 122MB (2015) -> 72MB (2016). As such, I suspect there will not be drastic differences for de-en across years.

-T
