### ISSUE TITLE
Question concerning <s> and <\s> tokens

### ISSUE THREAD

**Issue by nave01314** [tensorflow/nmt#192]
Note that `[` and `]` stands for `<` and `>` in this comment since arrows are used for formatting.

Based on the tutorial, the data pipeline is set up ending in the following line of code:
`((source, source_lengths), (target, target_lengths)) = batched_iterator.get_next()`
where `source` is a padded batch and `target` is a padded batch (no [s] or [/s] tokens appended)

However, placeholders are described at the top of the tutorial as if they already have these tokens:
```
    encoder_inputs [max_encoder_time, batch_size]: source input words.
    decoder_inputs [max_decoder_time, batch_size]: target input words.
    decoder_outputs [max_decoder_time, batch_size]: target output words, these are decoder_inputs shifted to the left by one time step with an end-of-sentence tag appended on the right.
```
or see image: https://github.com/tensorflow/nmt/blob/master/nmt/g3doc/img/seq2seq.jpg

How should the start/end tokens be appended? It seems like `decoder_inputs` should be shifted to the right and receive a [s] tag at the beginning before being embedded, and `decoder_outputs` should receive a [/s] tag at the end, but this is never mentioned in the explanation.

**Comment by oahziur** [comment]
@nave01314 The inputs and outputs preparations are implemented in [iterator_utils.py](https://github.com/tensorflow/nmt/blob/master/nmt/utils/iterator_utils.py) as linked in the tutorial.

Specifically, The decoder inputs and outputs are shifted [here](https://github.com/tensorflow/nmt/blob/master/nmt/utils/iterator_utils.py#L142).

**Comment by nave01314** [comment]
Thank you! It might be useful to leave a mention in the Data Preparation section of the explanation to clarify that Tensorflow does not intrinsically append tokens as part of the encoding/decoding process.
