### ISSUE TITLE
en-zh or zh-en translation

### ISSUE THREAD

**Issue by mingfengwuye** [tensorflow/nmt#20]
Is there any tutorial for en-zh or zh-en translation? How to get train and eval dataset for this translation?

**Comment by lmthang** [comment]
Hi @mingfengwuye,

You can modify this script https://github.com/tensorflow/nmt/blob/master/nmt/scripts/wmt16_en_de.sh to get the English-Chinese data here http://www.statmt.org/wmt17/translation-task.html.

Hope that helps.

**Comment by mingfengwuye** [comment]
@lmthang It seems to work well. I download the dev and test sets from wmt17. It contains zh-en dev and test data. And I use training-parallel-nc-v12 set to train the model. It seems to work well. Thank you.

**Comment by lmthang** [comment]
Great to hear!

**Comment by zhangpengGenedock** [comment]
@mingfengwuye how to change the script to train zh-en? can you show the full version changed script? thank you very much!

**Comment by parahaoer** [comment]
how to use BPE to segment Chinese data？

**Comment by fooSynaptic** [comment]
for people cannot find the zh-en corpus i present the direct link below: 
[https://conferences.unite.un.org/UNCorpus/en/DownloadOverview](url)

**Comment by zkl99999** [comment]
thank you @fooSynaptic
