### ISSUE TITLE
Expected state to be instance of AttentionWrapperState. Received type <class 'tuple'> instead.

### ISSUE THREAD

**Issue by ngcabang** [tensorflow/nmt#205]
Hi, I'm new to TensorFlow and trying to write my own seq2seq based on the tutorial provided. But unfortunately I am in the the error stated above. 

This is the part of the code

`attention_states = tf.transpose(encoder_outputs, [1, 0, 2])
attention_mechanism = tf.contrib.seq2seq.LuongAttention(300, encoder_outputs,
                                                        memory_sequence_length=source_lengths)

decoder_cell = tf.contrib.seq2seq.AttentionWrapper(decoder_cell, attention_mechanism, attention_layer_size=300)

projection_layer = tf.layers.Dense(dec_vocab_size, use_bias=False)
dec_embed_input = tf.nn.embedding_lookup(dec_embeddings, target)
helper = tf.contrib.seq2seq.TrainingHelper(dec_embed_input, target_lengths, time_major=True)
decoder = tf.contrib.seq2seq.BasicDecoder(cell=decoder_cell, helper=helper,
                                          initial_state=encoder_state,
                                          output_layer=projection_layer)
max_decoder_length = tf.reduce_max(target_lengths)

decoder_outputs, _ , _= tf.contrib.seq2seq.dynamic_decode(decoder=decoder, maximum_iterations=max_decoder_length)`

The trace error points on this:

`decoder_outputs, _ , _= tf.contrib.seq2seq.dynamic_decode(decoder=decoder, maximum_iterations=max_decoder_length)`

**Comment by jintaojintao** [comment]
do you solve this problem?

**Comment by ngcabang** [comment]
Yes, by setting the initial state in this line

`decoder = tf.contrib.seq2seq.BasicDecoder(cell=decoder_cell, helper=helper, initial_state=encoder_state, output_layer=projection_layer)`

with 

`initial_state = decoder_cell.zero_state(dtype=tf.float32, batch_size=batch_size)`

But, I don't know if is the right way to fix it, but it worked for me.

**Comment by oahziur** [comment]
@ngcabang @jintaojintao 

For the attention decoder cell's initial state, you can create a zero state and then copy the encoder's cell state. 

[Here](https://github.com/tensorflow/nmt/blob/365e7386e6659526f00fa4ad17eefb13d52e3706/nmt/attention_model.py#L131) is an example how NMT handles this. Alternatively, you can use zero state and fully rely on attention mechanism for decoding as ngcabang's solution.

**Comment by ziruizhuang** [comment]
@oahziur on passing encoder's cell state, I tried 
```
decoder_initial_state = decoder_cell.zero_state(batch_size, tf.float32).clone(
    cell_state=encoder_state
)
decoder = tf.contrib.seq2seq.BasicDecoder(
    decoder_cell,
    train_helper,
    decoder_initial_state,
    output_layer=projection_layer
)
```
where decoder_cell is a <tensorflow.contrib.seq2seq.python.ops.attention_wrapper.AttentionWrapper> object. And I still got the same error message. Any idea what the problem is in my code? 
Thx.

**Comment by PanXiebit** [comment]
execuse me, but when the when eager execution is enabled. How can you clone the encoder's cell state to the attention decode cell? 

when I use `decoder_initial_state = cell.zero_state(batch_size, dtype).clone(cell_state=encoder_state)` I get the error:  `Tensor.op is meaningless when eager execution is enabled.`
