### ISSUE TITLE
Training is not using GPU

### ISSUE THREAD

**Issue by denisb411** [tensorflow/nmt#228]
Why is this happening? Training is too slow on CPU:0...

How can I set gpu:0 ?

![image](https://user-images.githubusercontent.com/13735079/34484361-5ad2a026-efab-11e7-9036-be12e10234e4.png)

![image](https://user-images.githubusercontent.com/13735079/34484384-7d26b4aa-efab-11e7-8ea4-88358b306f89.png)

**Comment by oahziur** [comment]
`IteratorGetNext` is part of your input pipeline, so it is running on CPU. You can get detail device placement information by setting `--log_device_placement=True`.

**Comment by denisb411** [comment]
So the training is indeed made on GPU (if avaible)?

**Comment by oahziur** [comment]
@denisb411 you can check GPU utilization to confirm it is using GPU. You can also set `--num_gpus=0` compare the speed with CPU only training.

**Comment by lmthang** [comment]
Close for now due to no further activity.
