### ISSUE TITLE
Unable to setup the English to French Model (https://www.tensorflow.org/versions/r0.12/tutorials/seq2seq/) on Windows Server 2016

### ISSUE THREAD

**Issue by frajos100** [tensorflow/nmt#229]
Unable to setup the English to French Model (https://www.tensorflow.org/versions/r0.12/tutorials/seq2seq/) on Windows Server 2016. Error indicates that we would need Python 2.7.4 as per link  https://github.com/tensorflow/models/issues/1597.
Searched for the tensorflow version that python 2.7.4 supports. Not finding any solution and hence have opened an issue.

**Comment by lmthang** [comment]
Hi, do you still encounter the problem? Perhaps, you can try running with Python 3.5 https://www.tensorflow.org/install/install_windows? If you have managed to solve it, can you post your solution?

**Comment by frajos100** [comment]
Sorry as it was taking too much time to figure out with no proper support. Hence we had left doing R&D and perform a workaround without Tensorflow.

**Comment by lmthang** [comment]
Thanks for letting us know. I'll close this for now.
