### ISSUE TITLE
Tensorflow version error

### ISSUE THREAD

**Issue by yash2396** [tensorflow/nmt#235]
I have tensorflow 1.2.
When I proceed with the steps as in the tutorial I get the following error

python -m nmt.nmt \
>     --src=vi --tgt=en \
>     --vocab_prefix=/tmp/nmt_data/vocab  \
>     --train_prefix=/tmp/nmt_data/train \
>     --dev_prefix=/tmp/nmt_data/tst2012  \
>     --test_prefix=/tmp/nmt_data/tst2013 \
>     --out_dir=/tmp/nmt_model \
>     --num_train_steps=12000 \
>     --steps_per_stats=100 \
>     --num_layers=2 \
>     --num_units=128 \
>     --dropout=0.2 \
>     --metrics=bleu
Traceback (most recent call last):
  File "/home/yash/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/yash/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/yash/nmt/nmt/nmt.py", line 28, in <module>
    from . import inference
  File "/home/yash/nmt/nmt/inference.py", line 24, in <module>
    from . import attention_model
  File "/home/yash/nmt/nmt/attention_model.py", line 22, in <module>
    from . import model
  File "/home/yash/nmt/nmt/model.py", line 31, in <module>
    utils.check_tensorflow_version()
  File "/home/yash/nmt/nmt/utils/misc_utils.py", line 34, in check_tensorflow_version
    raise EnvironmentError("Tensorflow version must >= %s" % min_tf_version)
OSError: Tensorflow version must >= 1.4.0-dev20171024

What should I do.
I am skeptical a bout updating tensorflow since in many online sources I have read that tensorflow 1.4gpu has issues with CUDA.
Please advice.
If I have to update tensorflow, i would be glad if someone can guide me with the steps for it.
Thank You

**Comment by htpauleta** [comment]
This version of the tutorial requires TensorFlow Nightly. For using the stable TensorFlow versions, please consider other branches such as tf-1.4.

**Comment by yash2396** [comment]
But how to update tensorflow from 1.2 to 1.4.
I am using the anaconda version of tensorflow

**Comment by zp672087110** [comment]
pip install  --upgrade tensorflow
