### ISSUE TITLE
During GNMT 8LSTM training, can we train on full paragraphs, or must we break it to sentences?

### ISSUE THREAD

**Issue by nadavb** [tensorflow/nmt#236]
During GNMT 8LSTM training, can we train on full paragraphs (from source language to target language), or must we break it to sentences?

Can the model be trained well to cope will full paragraphs?

**Comment by lmthang** [comment]
In our experiments, we can train on longer sequences, e.g., lengths 200-400 (though depending on your model sizes, you might run out of memory). Training on long sequences will also take longer time. Running experiments is the best way to answer your question :)

**Comment by nadavb** [comment]
Thanks. I found it beneficial to train on around 3 sentences, in order to provide some beyond-sentence context to the model.

**Comment by lmthang** [comment]
Thanks for the info! Closing this for now.
