### ISSUE TITLE
Beam Search Decoder outputs -1 as prediction (how is this possible?)

### ISSUE THREAD

**Issue by evanweissburg** [tensorflow/nmt#246]

**Comment by Aashit-Sharma** [comment]
did you try using the FinalBeamSearchDecoderOutput instead of dynamic decode ? https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/FinalBeamSearchDecoderOutput

**Comment by classicCoder16** [comment]
Is there any update on this? I'm running into the same issue...

**Comment by Ravi-Jay** [comment]
Is there any update on this? @nave01314 Did you figure out how to resolve the error? I'm running into the same issue...

**Comment by tomhosking** [comment]
It looks like `dynamic_decode()` pads the output with `-1` outside of the valid length. The lengths are returned by `dynamic_decode()` as the third variable, so you can use that to mask the output or only use the valid parts of each decoded sequence.
