### ISSUE TITLE
[Question] Does nmt support eager execution?

### ISSUE THREAD

**Issue by howardyclo** [tensorflow/nmt#249]
Does nmt support eager execution?

**Comment by oahziur** [comment]
Hi @howardyclo, this tutorial doesn't support eager execution mode. Thanks!

**Comment by dmoham1476** [comment]
Any pointers on how to modify the nmt tutorial for eager?

**Comment by nthakor** [comment]
@oahziur  Is there a plan to support eager execution in future?
