### ISSUE TITLE
Cannot download data

### ISSUE THREAD

**Issue by fotwo** [tensorflow/nmt#256]
I used the script 'nmt/scripts/download_iwslt15.sh' to download data, but it seems the website 'https://nlp.stanford.edu/projects/nmt/' is not accessible. Can anyone solve this problem? In addition, I have found this repo 'https://github.com/stefan-it/nmt-en-vi' to get the parallel text without the vocab. Could anyone help me to get the vocab? Thanks a lots!

**Comment by ptamas88** [comment]
it's available again

**Comment by lmthang** [comment]
Yes, Stanford NLP server was down a few days ago, so closing.
