### ISSUE TITLE
Attention output is not passed through tanh()

### ISSUE THREAD

**Issue by khanhptnk** [tensorflow/nmt#257]
self._attention_layer in AttentionWrapper is just a linear layer with no non-linear activation. This is difference from Luong et al., 2015 where this is a non-linear layer with tanh() activation. Is it a coding mistake or a design choice?

https://github.com/tensorflow/nmt/blob/master/nmt/model.py#L105

**Comment by lmthang** [comment]
Yeah, we missed this tanh() so you can call it a coding mistake [ though we can still train models just fine, the magic of neural networks :) ] We'll consider adding a flag so people can specify the activation for attention layer as in the original paper.

**Comment by khanhptnk** [comment]
Thanks for the reply. I also found that this bug didn't really affect the results. Also thanks for the repo, I learned a lot when trying match the performance of your code :)
