### ISSUE TITLE
BPE support seems missing

### ISSUE THREAD

**Issue by skyw** [tensorflow/nmt#4]
I'm trying to run wmt16_en_de_gnmt.json.
It first comes back with an error of missing vocabulary file. Looking into the code, it doesn't look for the vocab files with "bpe.32000" which are created by the wmt16_en_de.sh. If I force it to look at the right vocab file, then the model starts to run and graph build seems successful. However, it stops with an error "HashTable has different value for same key. Key \<s\> has 1 and trying to add value 4"

**Comment by skyw** [comment]
It seems train/test/dev data load don't have BPE path neither.

**Comment by ebrevdo** [comment]
@lmthang Can you PTAL?

**Comment by lmthang** [comment]
@skyw: can you provide the error log?

**Comment by skyw** [comment]
[test.log.txt](https://github.com/tensorflow/nmt/files/1153324/test.log.txt)

Attached. the command I used is at beginning of the log. 
It looks the BPE vocab files contains <s>, </s> already, while the vocab_utils.py is not aware of any of them.

**Comment by oahziur** [comment]
Hmm, why the first token in your vocab is "-e unk", is there any compatibility issues on the vocab generation?

I believe the 3 special token is appended here:

https://github.com/tensorflow/nmt/blob/master/nmt/scripts/wmt16_en_de.sh#L148

**Comment by siddharthbhatnagar** [comment]
@oahziur I also have a question about BPE.

In the WMT German-English benchmarks section, it is mentioned that 'The data is split into subword units using BPE (32K operations).'

My question is, during these benchmark BLEU score calculations, are the comparisons made BPE vs BPE (i.e. targets and predictions both using BPE segmentation)?  Or do you apply original segmentation to both targets and predictions by using 'sed -r 's/(@@ )|(@@ ?$)//g'' (as per https://github.com/rsennrich/subword-nmt) and THEN calculate BLEU?

**Comment by skyw** [comment]
Though they look pretty much the same, I still used https://github.com/tensorflow/nmt/blob/master/nmt/scripts/wmt16_en_de.sh to generate data instead of the one I generated by tensor2tensor's script.
But anyway, I removed "-e", it still reports the same error.

**Comment by oahziur** [comment]
@skyw Can you try remove "-e " and a fresh `out_dir`. I think the model will use previous saved vocab_file.

Also, here is the head of the vocab file:
```
<unk>
<s>
</s>
,
.
the
in
of
and
die
```

**Comment by skyw** [comment]
Uh, it seems to be working after I deleted the the out_dir. Sorry for the chatter, I should have done that.

I also tried to reproduce the issue of generating "-e" in the vocab file. I think the problem is the space between # and !, https://github.com/tensorflow/nmt/blob/master/nmt/scripts/wmt16_en_de.sh#L1
