### ISSUE TITLE
about debug

### ISSUE THREAD

**Issue by gzpan** [tensorflow/nmt#41]
There is no problem running the nmt example in shell windows with 'python -m nmt.nmt ......' comands.
but how can i debug the code in anaconda environment?  I get some relative path import problem when
I try to debug the nmt.py file.
    Run the nmt.py directly will cause an empty __package__, so it's impossible to execute import statements
like 'from . import inference' and so on.
So what is the reason that the example use relative import way? it is hard for users to debug

**Comment by liukecai** [comment]
I have met this problem, how do you solve it?
