### ISSUE TITLE
I can't use beamsearch

### ISSUE THREAD

**Issue by chuangfortytwo** [tensorflow/nmt#43]
I got a error when I set beam_width=10 or load hparams from the standard_hparams

```
InvalidArgumentError (see above for traceback): Multiple OpKernel registrations match NodeDef 'dynamic_seq2seq/decoder/decoder/GatherTree = GatherTree[T=DT_INT32](dynamic_seq2seq/decoder/decoder/TensorArrayStack_1/TensorArrayGatherV3, dynamic_seq2seq/decoder/decoder/TensorArrayStack_2/TensorArrayGatherV3, dynamic_seq2seq/decoder/decoder/while/Exit_16)': 'op: "GatherTree" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } }' and 'op: "GatherTree" device_type: "CPU" constraint { name: "T" allowed_values { list { type: DT_INT32 } } }'
	 [[Node: dynamic_seq2seq/decoder/decoder/GatherTree = GatherTree[T=DT_INT32](dynamic_seq2seq/decoder/decoder/TensorArrayStack_1/TensorArrayGatherV3, dynamic_seq2seq/decoder/decoder/TensorArrayStack_2/TensorArrayGatherV3, dynamic_seq2seq/decoder/decoder/while/Exit_16)]]
```

**Comment by oahziur** [comment]
@chuangfortytwo Can you provide your python version and tensorflow version? Thanks.

**Comment by chuangfortytwo** [comment]
@oahziur My python version is“Python 3.5.3 “and tensorflow version is "1.2.1: .Thanks

**Comment by ebrevdo** [comment]
@chuangfortytwo how did you install tensorflow and how are you loading it?  what operating system are you using?

multiple op registrations may happen if you try to load the dynamic library that contains the GatherTree op twice.  i believe the line in question is [this one](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/ops/beam_search_ops.py#L24).

please also provide a full stacktrace of the error and relevant parts of your code.
