### ISSUE TITLE
Question: How to set the encoding to prevent unexpected conversion?

### ISSUE THREAD

**Issue by yanl10n** [tensorflow/nmt#44]
While following the tutorial, i met two issues as below. Would you please share me your comments and suggestions? thanks in advance!

1) Encoding?
The target strings were converted into unicode such as "B\xc2\xa0..." I notice that in the tutorial, text should be displayed as they are (for example, Vietnamese text). I use ubuntu x64 + python 3.5. The default encoding of system is UTF-8. Any idea for what I might do wrong here? 
![issue01](https://user-images.githubusercontent.com/30624822/28823838-1f285b60-76f2-11e7-8b39-9a7aa7c36d86.png)

2) Errors as below.
There's no error during the training, however we cannot use the trained module and get errors as below. I guess it might relate to the first issue but i cannot figure out where exactly goes wrong. Any suggestion would be welcome
![issue02](https://user-images.githubusercontent.com/30624822/28823839-1f31b9a8-76f2-11e7-9f9e-85362b31a7c4.png)

**Comment by chuangfortytwo** [comment]
我在pycharm上输出时加了decode（’utf-8‘）解决了，但是看其它人都没遇到这个问题很奇怪

**Comment by oahziur** [comment]
For 1, I think it is because the tutorial logs are generated by python2. I will investigate later to make the logging works correctly for both python2 and 3.

For 2, We recently updated the flags. Change `model_dir` to `out_dir` should fix the problem.  For example

```

python -m nmt.nmt \
    --out_dir=/tmp/nmt_model \
    --inference_input_file=/tmp/my_infer_file.vi \
    --inference_output_file=/tmp/nmt_model/output_infer
```

**Comment by yanl10n** [comment]
Thank you @chuangfortytwo @oahziur! I would try today and share you the result later.

**Comment by anglil** [comment]
I tried the vietnamese to english translation in the tutorial and get decoder output all in byte string format, i.e., string with a 'b' in front of it. Is this the expected behavior? Should I manually convert the output strings into utf-8? Thanks!

**Comment by sdlmw** [comment]
@chuangfortytwo ,那能不能在输出到文件的时候就给转码了（抱歉，pycharm没有接触过），还有如果加载到一个服务上，是否可以输出转码的内容

**Comment by chuangfortytwo** [comment]
@sdlmw 最后计算bleu值的时候就是从文件读取的，可以在输出到文件时转码。服务这个没试过

**Comment by luosmart** [comment]
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

**Comment by yanl10n** [comment]
Thank you All for the supports! Confirmed all issues had been fixed now.
