### ISSUE TITLE
ImportError: cannot import name inference (not duplicate)

### ISSUE THREAD

**Issue by nave01314** [tensorflow/nmt#46]
I checked the older issue https://github.com/tensorflow/nmt/issues/39 that seemed similar to this error, but as cloned, I don't have a `gnmt-master` to move up into as suggested.

When I cloned into Intellij, I ended up with the path ~\IdeaProjects\nmt\nmt\nmt.py as the entry point.

Screenshot of issue, project structure, and run configuration: http://imgur.com/RVNDhf0

**Comment by fansiawang** [comment]
You can execute the following command to test your model:
```
python -m nmt.nmt \
     		--src=vi --tgt=en \
     		--vocab_prefix=./nmt/nmt_data/vocab  \
     		--out_dir=./nmt//nmt_attention_model \
     		--model_dir=./nmt//nmt_model \
     		--inference_input_file=./nmt//my_infer_file.vi \
    		--inference_output_file=./nmt//nmt_attention_model/output_infer
```
I use this command to test my model successfully. This command can also be found in the NMT tutorial, but it will be some different.  Maybe you can try both of them. Hope that can help you!

**Comment by nave01314** [comment]
@fansiawang I'm currently running with `~\IdeaProjects\nmt\` as my project directory, so I'm not sure what you mean by moving up one directory to the first "nmt". Can you clarify?

**Comment by nave01314** [comment]
I'd like to bump this @fansiawang. Still having the same issue.
![screenshot 2](https://user-images.githubusercontent.com/19654723/32021453-693d15dc-b9a1-11e7-82ec-60e25835c106.png)

**Comment by gloriouskilka** [comment]
@nave01314 Hello!
There is `python -m nmt.nmt` command line in the README.md, so you need to change "Script" to "Module" (Just below "Configuration" tab name) in IDEA and pass `nmt.nmt` instead of `D:\Stuff\....\nmt.py`

**Comment by nave01314** [comment]
Config as below:

```
Script: (nothing is here)
Script parameters: (nothing is here)
...
Interpreter options: -m nmt.nmt
Working directory: /home/nave01314/IdeaProjects/tensornmt
```

**Comment by elham1996** [comment]
I try a lot to fix these issues but nothing work what should I do?

**Comment by leqnam** [comment]
Let's say
```
root
|_CONTRIBUTING.md
|_README.MD
|_nmt
  |_nmt.py
  |_...
```

Then, move up to the root and then run:
```
py -m nmt.nmt
```
