### ISSUE TITLE
Is the decoder output in its BPE-ed form? 

### ISSUE THREAD

**Issue by anglil** [tensorflow/nmt#47]
Does one need to combine word pieces in the decoder output together on their own, in order to get the final translation hypothesis?

**Comment by oahziur** [comment]
The raw output from [model.decode](https://github.com/tensorflow/nmt/blob/master/nmt/model.py#L438) is in BPE form if the input data are in BPE form.

We use [nmt_utils.get_translation](https://github.com/tensorflow/nmt/blob/master/nmt/utils/nmt_utils.py#L85) to convert the raw output to final translation.

**Comment by anglil** [comment]
@oahziur Thanks!
