### ISSUE TITLE
Dev dataset cannot be very large?

### ISSUE THREAD

**Issue by fansiawang** [tensorflow/nmt#48]
If I use a large dev dataset, then the code will crash. And it will be cost much time during the following command:
`I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator:`
After l long time ,it will crash, the error log is as follows:
`Resource exhausted: OOM when allocating tensor with shape[23296,47291]`
But if I change the dev dataset to a small one ,then it will work successfully.
I'm not sure if I have a problem with my operation or the code cannot use a large dev dataset.
Does anybody know how to solve this problem? Thank you very much!

**Comment by chuangfortytwo** [comment]
You need a GPU with bigger memory
