### ISSUE TITLE
When decoding, is the latest model selected or the one with the highest bleu on dev?  

### ISSUE THREAD

**Issue by anglil** [tensorflow/nmt#53]
If it is not the one with the highest bleu on dev that's selected, how do I enforce the selection of the model with the highest bleu on dev? Thanks.

**Comment by oahziur** [comment]
For training, the best_dev model will be evaluated once the training loop is done.

For inference, the default is the latest checkpoint in out_dir, but you can use `--ckpt` flag to specify the checkpoint path. For example:

```
python -m nmt.nmt \
    --out_dir=/tmp/nmt_model \
    --ckpt=/path/to/checkpoint/translate.ckpt \
    --inference_input_file=/tmp/my_infer_file.vi \
    --inference_output_file=/tmp/nmt_model/output_infer
```

**Comment by anglil** [comment]
Thanks!
