### ISSUE TITLE
OOM due to large target vocab.

### ISSUE THREAD

**Issue by rajarsheem** [tensorflow/nmt#56]
I am facing a OOM error due to the target vocab size being very large. Any idea how to tackle this ?
Maybe somehow using ```sampled_softmax_loss``` after decoding ?

**Comment by aracthon** [comment]
@rajarsheem Hi, I met the same problem. My GPU memory is 8GB. I tried to set a smaller batch_size from original 128 to 16, then everything works fine. You could set it by adding `--batch_size=16` (or 32, 64).

**Comment by rajarsheem** [comment]
I am using ```sampled_softmax_loss```. Not sure if it is hurting performance.

**Comment by ZixuanLiang** [comment]
@rajarsheem How is the performance when you use sampled_softmax_loss? Did you use smaller batch size as suggested by @aracthon? @aracthon How is the performance when you use smaller batch size?
