### ISSUE TITLE
how can the attention distribution from the encoder side be exposed?

### ISSUE THREAD

**Issue by rajarsheem** [tensorflow/nmt#68]
I wanted to get access to the attention distribution for the encoder states corresponding to each decoder time step. How can this be achieved ?

**Comment by AlexGuoHan** [comment]
The alignment_history attribute of the AttentionWrapperState stores all the attention distribution in past time steps.

**Comment by rajarsheem** [comment]
@AlexGuoHan Where will get the history as return ?

**Comment by AlexGuoHan** [comment]
In the `attention_mode.py` you will find at the end of the file:
```
def _create_attention_images_summary(final_context_state):
  """create attention image and attention summary."""
  attention_images = (final_context_state.alignment_history.stack())
  # Reshape to (batch, src_seq_len, tgt_seq_len,1)
  attention_images = tf.expand_dims(
      tf.transpose(attention_images, [1, 2, 0]), -1)
  # Scale to range [0, 255]
  attention_images *= 255
  attention_summary = tf.summary.image("attention_images", attention_images)
  return attention_summary
```
The third line `attention_images = (final_context_state.alignment_history.stack())` will create an array of  attention distributions.

**Comment by rajarsheem** [comment]
I called stack() on the ```alignment_history``` attribute of ```AttentionWrapperState``` which is coming out of the ```dynamic_decode```.

**Comment by rajarsheem** [comment]
[contd.] which is of shape ```[decoder_length, batch_size, encoder_length]```

**Comment by AlexGuoHan** [comment]
Do a reshape, `tf.transpose(attention_images, [1, 2, 0])`. This will produce an array of shape `batch_size, encoder_len, decoder_len`.

**Comment by rajarsheem** [comment]
Yeah, exactly.
