### ISSUE TITLE
Is it possible to run this in Windows? 

### ISSUE THREAD

**Issue by PasinduTennage** [tensorflow/nmt#70]

**Comment by bingq** [comment]
Just wondering how your result is ? 
BTW I tried in ubuntu.

**Comment by Yijun0509** [comment]
It's been 2 months after this question was posted but I just want to say yes! I had a lot of problems running this project in windows but it finally worked!

**Comment by CorneliusHagmeister** [comment]
I am also trying to get it to work in windows. @Yijun0509 Could you say a little bit about what you had to change? It seems, that it won't load the necessary files, when I try to run one of the examples.
